AWSTemplateFormatVersion: '2010-09-09'
Description: Parent template to deploy foundational and dependent resources.

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., Dev, Prod).
  FoundationTemplateS3Uri:
    Type: String
    Description: S3 URI of the arch-foundation.yaml template.
  ClientPublicDBTemplateS3Uri:
    Type: String
    Description: S3 URI of the arch-foundation.yaml template.
  ClientPublicAppS3Uri:
    Type: String
    Description: S3 URI of the child template requiring foundation outputs.
  PaypalProcessorS3Uri:
    Type: String
    Description: S3 URI of the child template requiring foundation outputs.
  AdminAppS3Uri:
    Type: String
    Description: S3 URI of the child template requiring foundation outputs.
  EmailIdentityRecipientEmail:
    Type: String
    Description: Email address to receive notifications.
  EmailIdentitySenderEmail:
    Type: String
    Description: Email address to send notifications.
  PaypalSecret:
    Type: String
    Description: Paypal secret.
  PayPalClientId:
    Type: String
    Description: Paypal client id.
  Repository:
    Type: String
    Description: URL of the Git repository (e.g., https://github.com/user/repo)
  Branch:
    Type: String
    Description: Branch to deploy from (e.g., main)
  OauthToken:
    Type: String
    Description: GitHub Personal Access Token
  DomainName:
    Type: String
    Description: Domain name for the application
  PaypalAuthTokenLink:
    Type: String
    Description: URL to retrieve the paypal auth token
  PaypalCheckoutOrderLink:
    Type: String
    Description: URL to retrieve the paypal checkout order
  PaypalCatalogueProductLink:
    Type: String
    Description: URL to retrieve the paypal catalogue product
  PaypalBillingPlansLink:
    Type: String
    Description: URL to retrieve the paypal billing plans
  PaypalBillingSubscriptionLink:
    Type: String
    Description: URL to retrieve the paypal billing subscription

Resources:
  ArchFoundationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref FoundationTemplateS3Uri
      Parameters:
        Environment: !Ref Environment
  
  ClientPublicDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ClientPublicDBTemplateS3Uri
      Parameters:
        Environment: !Ref Environment

  ClientPublicAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ClientPublicAppS3Uri
      Parameters:
        Environment: !Ref Environment
        UserPoolId: !GetAtt ArchFoundationStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt ArchFoundationStack.Outputs.UserPoolClientId
        SESConfigurationSetName: !GetAtt ArchFoundationStack.Outputs.SESConfigurationSet
        EmailIdentityRecipientEmail: !Ref EmailIdentityRecipientEmail
        EmailIdentitySenderEmail: !Ref EmailIdentitySenderEmail
        PaypalSecret: !Ref PaypalSecret
        PayPalClientId: !Ref PayPalClientId
        Repository: !Ref Repository
        Branch: !Ref Branch
        OauthToken: !Ref OauthToken
        DomainName: !Ref DomainName
        PaypalAuthTokenLink: !Ref PaypalAuthTokenLink
        PaypalCheckoutOrderLink: !Ref PaypalCheckoutOrderLink
        PaypalCatalogueProductLink: !Ref PaypalCatalogueProductLink
        PaypalBillingPlansLink: !Ref PaypalBillingPlansLink
        PaypalBillingSubscriptionLink: !Ref PaypalBillingSubscriptionLink

  PaypalProcessorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PaypalProcessorS3Uri
      Parameters:
        Environment: !Ref Environment
        TableName: !GetAtt ClientPublicDBStack.Outputs.SubscriptionsAndPaymentsTableName

  AdminAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref AdminAppS3Uri
      Parameters:
        Environment: !Ref Environment
        TableName: !GetAtt ClientPublicDBStack.Outputs.SubscriptionsAndPaymentsTableName
        UserPoolId: !GetAtt ArchFoundationStack.Outputs.UserPoolId

Outputs:
  ArchFoundationStackId:
    Description: Stack ID of the foundational resources.
    Value: !Ref ArchFoundationStack

  ClientPublicDBStackId:
    Description: Stack ID of the Database stack resources.
    Value: !Ref ClientPublicDBStack

  ClientPublicAppStackId:
    Description: Stack ID of the App resources.
    Value: !Ref ClientPublicAppStack

  PaypalProcessorStackId:
    Description: Stack ID of the processor resources.
    Value: !Ref PaypalProcessorStack