AWSTemplateFormatVersion: '2010-09-09'
Description: Parent template to deploy foundational and dependent resources.

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., Dev, Prod).
  FoundationTemplateS3Uri:
    Type: String
    Description: S3 URI of the arch-foundation.yaml template.
  ClientPublicDBTemplateS3Uri:
    Type: String
    Description: S3 URI of the arch-foundation.yaml template.
  ClientPublicAppS3Uri:
    Type: String
    Description: S3 URI of the child template requiring foundation outputs.
  PaypalProcessorS3Uri:
    Type: String
    Description: S3 URI of the child template requiring foundation outputs.
  EmailIdentityRecipientEmail:
    Type: String
    Description: Email address to receive notifications.
  EmailIdentitySenderEmail:
    Type: String
    Description: Email address to send notifications.
  PaypalSecret:
    Type: String
    Description: Paypal secret.
  PayPalClientId:
    Type: String
    Description: Paypal client id.
  SpreadSheetId:
    Type: String
    Description: Google spreadsheet id.
  Repository:
    Type: String
    Description: URL of the Git repository (e.g., https://github.com/user/repo)
  Branch:
    Type: String
    Description: Branch to deploy from (e.g., main)
  OauthToken:
    Type: String
    Description: GitHub Personal Access Token
  DomainName:
    Type: String
    Description: Domain name for the application

Resources:
  ArchFoundationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref FoundationTemplateS3Uri
      Parameters:
        Environment: !Ref Environment
  
  ClientPublicDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ClientPublicDBTemplateS3Uri
      Parameters:
        Environment: !Ref Environment

  ClientPublicAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ClientPublicAppS3Uri
      Parameters:
        Environment: !Ref Environment
        UserPoolId: !GetAtt ArchFoundationStack.Outputs.UserPoolId
        SESConfigurationSetName: !GetAtt ArchFoundationStack.Outputs.SESConfigurationSet
        EmailIdentityRecipientEmail: !Ref EmailIdentityRecipientEmail
        EmailIdentitySenderEmail: !Ref EmailIdentitySenderEmail
        PaypalSecret: !Ref PaypalSecret
        PayPalClientId: !Ref PayPalClientId
        Repository: !Ref Repository
        Branch: !Ref Branch
        OauthToken: !Ref OauthToken
        DomainName: !Ref DomainName

  PaypalProcessorStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref PaypalProcessorS3Uri
      Parameters:
        Environment: !Ref Environment
        SpreadSheetId: !Ref SpreadSheetId

Outputs:
  ArchFoundationStackId:
    Description: Stack ID of the foundational resources.
    Value: !Ref ArchFoundationStack