AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 Buckets and Lambda Functions for Workload Application using AWS SAM

Parameters:
  Environment:
    Type: String
    Default: Dev
    Description: Environment name for the VPC
  
  SpreadSheetId:
    Type: String
    Description: Google spreadsheet id.

Globals:
  Function:
    Runtime: python3.8
    Handler: index.lambda_handler
    Timeout: 30
    Tags:
      Environment: !Ref Environment

Resources:
  ### Lambda Execution Role ###
  PayPalProcessorLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "PayPalProcessorRole-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        # Basic Lambda logging policy
        - PolicyName: BasicLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

        # DynamoDB Access Policy (optional if you still use DynamoDB)
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                Resource:
                  - "arn:aws:dynamodb:*:*:table/AdminTable"
                  - "arn:aws:dynamodb:*:*:table/SubscriptionsAndPayments"


          # SSM Parameter Store Access Policy
        - PolicyName: SSMParameterAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/rcw-paypal-processor-gcp-service-account"
      Tags:
        Infrastructure: RCW
        Component: Application
        Name: !Sub "RCW-PayPalProcessorLambdaExecutionRole-${Environment}"
        Environment: !Ref Environment

  PayPalProcessorFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: s3://rcw-code-bucket/paypal-processor/layer.zip

  ### Lambda Function for PayPal Processor ###
  PayPalProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "PayPal-Processor-${Environment}"
      Role: !GetAtt PayPalProcessorLambdaExecutionRole.Arn
      CodeUri: s3://rcw-code-bucket/paypal-processor/paypal-processor.zip
      Runtime: python3.8
      Layers:
      - !Ref PayPalProcessorFunctionLayer
      Environment:
        Variables:
          SPREADSHEET_ID: 1Jpicnmuuuy7aS__mGb-3sLgED9vxvELrvffrDtOHWjo
          SERVICE_ACCOUNT_PARAMETER_NAME: rcw-paypal-processor-gcp-service-account
      Events:
        PayPalWebhook:
          Type: Api
          Properties:
            Path: /paypal-webhook
            Method: POST
      Tags:
        Infrastructure: RCW
        Component: Application
        Name: RCW-PayPalProcessorFunction
        Environment: !Ref Environment
        Description: Lambda function for PayPal Processor which receives the webhook from PayPal and uploads donation data to data storage

Outputs:
  PayPalProcessorLambdaFunctionArn:
    Value: !GetAtt PayPalProcessorFunction.Arn
    Description: "Lambda function ARN for PayPal Processor"

  ApiEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/paypal-webhook"