name: Dynamic CloudFormation Update

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-changes-and-deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect changed files
        id: changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD~1 > changed_files.txt
          cat changed_files.txt
          echo "files=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Debug changed files
        run: echo "${{ env.files }}"

      - name: Deploy Foundation Template
        if: ${{ contains(env.files, 'infrastructure/workloads/arch-foundation.yaml') }}
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/workloads/arch-foundation.yaml \
            --stack-name RCW-Architecture-Foundation-Dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-execute-changeset \
            --region us-west-1 \
            --parameter-overrides \
                Environment=Dev

      - name: Clean Paypal Processor Build Directory
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-paypal-processor.yaml') }}
        run: rm -rf .aws-sam/paypal-processor

      - name: Build Paypal Processor
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-paypal-processor.yaml') }}
        run: |
          sam build \
            --template-file infrastructure/workloads/rcw-paypal-processor.yaml \
            --build-dir .aws-sam/paypal-processor

      - name: Deploy Paypal Processor Template
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-paypal-processor.yaml') }}
        run: |
          sam deploy \
            --template-file ".aws-sam/paypal-processor/template.yaml" \
            --stack-name RCW-Architecture-Paypal-Processor-Dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-execute-changeset \
            --region us-west-1 \
            --parameter-overrides Environment=Dev

      - name: Clean Web App Build Directory
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-app-layer.yaml') }}
        run: rm -rf .aws-sam/web-app

      - name: Build Web App
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-app-layer.yaml') }}
        run: |
          sam build \
            --template-file infrastructure/workloads/rcw-client-public-app-layer.yaml \
            --build-dir .aws-sam/web-app

      - name: Deploy Web App Template
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-app-layer.yaml') }}
        run: |
          sam deploy \
            --template-file ".aws-sam/web-app/template.yaml" \
            --stack-name RCW-Architecture-App-Dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-execute-changeset \
            --region us-west-1 \
            --parameter-overrides Environment=Dev

      - name: Clean DB Build Directory
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-db-layer.yaml') }}
        run: rm -rf .aws-sam/db

      - name: Build DB
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-db-layer.yaml') }}
        run: |
          sam build \
            --template-file infrastructure/workloads/rcw-client-public-db-layer.yaml \
            --build-dir .aws-sam/db

      - name: Deploy DB Template
        if: ${{ contains(env.files, 'infrastructure/workloads/rcw-client-public-db-layer.yaml') }}
        run: |
          sam deploy \
            --template-file ".aws-sam/db/template.yaml" \
            --stack-name RCW-Architecture-DB-Dev \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-execute-changeset \
            --region us-west-1 \
            --parameter-overrides Environment=Dev
