name: Dynamic CloudFormation Update

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect-changes-and-deploy:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect changed files
        id: changes
        run: |
          echo "Detecting file changes..."
          git fetch origin ${{ github.ref_name }} || true  # Ensure the branch is fully updated
          git diff --name-only HEAD~1 > changes_detected.txt
          cat changes_detected.txt | grep 'infrastructure/' > filtered_changes.txt || echo "no-changes" > filtered_changes.txt
          cat filtered_changes.txt

          if grep -q "no-changes" filtered_changes.txt; then
            echo "No changes detected in templates. Skipping deployment."
            echo "should_run=false" >> $GITHUB_ENV
          else
            echo "Changes detected in templates. Proceeding with deployment."
            echo "should_run=true" >> $GITHUB_ENV
          fi

      - name: Upload changed files to S3
        if: env.should_run == 'true'
        run: |
          echo "Uploading changed files to S3..."
          while read file; do
            if [[ $file == no-changes ]]; then
              echo "No changes detected. Skipping upload."
              exit 0
            fi

            # Determine S3 path based on file location
            if [[ $file == infrastructure/arch-foundation.yaml ]]; then
              s3_path="templates/arch-foundation.yaml"
            elif [[ $file == infrastructure/client-public-db.yaml ]]; then
              s3_path="templates/client-public-db.yaml"
            elif [[ $file == infrastructure/client-public-app.yaml ]]; then
              s3_path="templates/client-public-app.yaml"
            elif [[ $file == infrastructure/paypal-processor.yaml ]]; then
              s3_path="templates/paypal-processor.yaml"
            else
              echo "Unknown file: $file. Skipping."
              continue
            fi

            aws s3 cp "$file" "s3://rcw-code-bucket/$s3_path" --region us-west-1
          done < changed_files.txt

      - name: Deploy Parent Template
        if: env.should_run == 'true'
        run: |
          echo "Deploying parent template..."
          aws cloudformation deploy \
            --template-file infrastructure/rcw-infra.yaml \
            --stack-name RCW-Infrastructure-Prod \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region us-west-1 \
            --parameter-overrides \
              Environment=Prod \
              FoundationTemplateS3Uri=s3://rcw-code-bucket/templates/arch-foundation.yaml \
              ClientPublicDBTemplateS3Uri=s3://rcw-code-bucket/templates/client-public-db.yaml \
              ClientPublicAppS3Uri=s3://rcw-code-bucket/templates/client-public-app.yaml \
              PaypalProcessorS3Uri=s3://rcw-code-bucket/templates/paypal-processor.yaml \
              EmailIdentityRecipientEmail=emmanuelurias60@icloud.com \
              EmailIdentitySenderEmail=emmanuelurias60@nebulaawsconsulting.com \
              PaypalSecret=${{ secrets.PAYPAL_SECRET }} \
              PayPalClientId=${{ secrets.PAYPAL_CLIENT_ID }} \
              SpreadSheetId=1Jpicnmuuuy7aS__mGb-3sLgED9vxvELrvffrDtOHWjo \
              Repository=https://github.com/Nebula-AWS-Consulting/RCW-Infrastructure-Campaign \
              Branch=main \
              OauthToken=${{ secrets.OAUTH_TOKEN }} \
              DomainName=restoredchurchlv.org
